# Generated by Django 4.0.2 on 2025-07-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bio',
            field=models.CharField(default='No bio', max_length=255),
            preserve_default=False,
        ),
    ]
